# Sidebar navigation

- label: "Introduction"
  link: "/"

- label: "Team"
  items:
    - label: "Onboarding"
      link: "/team/onboarding"
    - label: "Book Club"
      link: "/team/book-club"
    - label: "Slack"
      link: "/team/slack"

- label: "Processes"
  items:
    - label: "New User Setup"
      link: "/processes/new-users"
    - label: "Web Design"
      link: "/processes/web-design"
    - label: "Takedown Requests"
      link: "/processes/takedown-requests"

- label: Social
  items:
    - label: "Website"
      link: https://www.iamtuf.org
    - label: "Instagram"
      link: https://www.instagram.com/iamtuf
    - label: "Facebook"
      link: https://www.facebook.com/iamtuf
    - label: "LinkedIn"
      link: https://www.linkedin.com/company/iamtuf
